"""
Django settings for lmhu_project project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")


def _required_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise ImproperlyConfigured(
            f"Missing required environment variable: {name}"
        )
    return value


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"true", "1", "yes", "on"}


def _env_list(name: str, default: str = "") -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_path(name: str) -> Path | None:
    value = os.getenv(name, "").strip()
    if not value:
        return None
    path = Path(value)
    return path if path.is_absolute() else BASE_DIR / path


# Quick-start development settings - unsuitable for production
SECRET_KEY = _required_env("DJANGO_SECRET_KEY")
DEBUG = _env_bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
)

# Local-only JWT login for the Flutter Web RAG demo. This always fails closed
# when Django debug mode is disabled.
LOCAL_DEMO_LOGIN = DEBUG and _env_bool("LOCAL_DEMO_LOGIN", default=False)
LOCAL_DEMO_USERNAME = (
    os.getenv("LOCAL_DEMO_USERNAME", "portfolio_demo").strip()
    or "portfolio_demo"
)
DEMO_MEDIA_ROOT = _env_path("DEMO_MEDIA_ROOT")
DEMO_FAISS_ROOT = _env_path("DEMO_FAISS_ROOT")


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'lmhu',

    'corsheaders',

    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS 먼저
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lmhu_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lmhu_project.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _required_env("DB_NAME"),
        'USER': _required_env("DB_USER"),
        'PASSWORD': _required_env("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "127.0.0.1").strip() or "127.0.0.1",
        'PORT': os.getenv("DB_PORT", "3306").strip() or "3306",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'


# Media and local vector indexes
MEDIA_URL = "/media/"
MEDIA_ROOT = (
    DEMO_MEDIA_ROOT
    if LOCAL_DEMO_LOGIN and DEMO_MEDIA_ROOT is not None
    else BASE_DIR / "media"
)
FAISS_ROOT = (
    DEMO_FAISS_ROOT
    if LOCAL_DEMO_LOGIN and DEMO_FAISS_ROOT is not None
    else BASE_DIR / "faiss"
)


# DRF (JWT 필수)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# CORS
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _env_list("CORS_ALLOWED_ORIGINS")


# RAG 관련 환경설정 (.env 에서 로드)
# OPENAI_API_KEY는 openai 라이브러리가 자동으로 os.environ에서 읽음
USE_RAG: bool = os.getenv('USE_RAG', 'false').lower() == 'true'
EMBED_MODEL: str = os.getenv('EMBED_MODEL', 'text-embedding-3-small')
TOP_K: int = int(os.getenv('TOP_K', 5))
CHUNK_SIZE = 700
CHUNK_OVERLAP = 100
RAG_DISTANCE_THRESHOLD = 1.2
OPENAI_MODEL: str = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # 리프레시 토큰 회전
    "ROTATE_REFRESH_TOKENS": True,

    # 회전 후 이전 리프레시 토큰은 블랙리스트 처리
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),
}
