# Generated by Django 5.2.6 on 2025-10-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhu', '0002_document_documentchunk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['doc', 'idx'], name='lmhu_docume_doc_id_f04639_idx'),
        ),
    ]
