# Generated by Django 5.2.6 on 2025-11-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhu', '0003_documentchunk_lmhu_docume_doc_id_f04639_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('path', models.CharField(max_length=500)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('score', models.FloatField(default=0)),
                ('caption', models.TextField(blank=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lmhu.document')),
            ],
            options={
                'ordering': ['-score', 'page'],
                'indexes': [models.Index(fields=['doc', 'page'], name='lmhu_docume_doc_id_bdfc72_idx')],
            },
        ),
    ]
