# Generated by Django 5.2.6 on 2026-04-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmhu', '0004_documentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='pages_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='doc_pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='lmhu.document')),
            ],
            options={
                'ordering': ['page'],
                'indexes': [models.Index(fields=['doc', 'page'], name='lmhu_docume_doc_id_6d3031_idx')],
                'unique_together': {('doc', 'page')},
            },
        ),
    ]
